config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  get "up" => "rails/health#show", as: :rails_health_check
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "member/:id", to: "members#show", as: :member
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  def name
    "#{first_name} #{last_name}".strip
  end

  def address
    return if city.blank? || state.blank? || country.blank? || pincode.blank?
    "#{city}, #{state}, #{country}, #{pincode}"
  end

  def self.ransackable_attributes(auth_object = nil)
    [ "country", "city" ]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @q = User.ransack(params[:q])
    @users = @q.result.limit(16).order(:created_at)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_user
  def show
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="col-lg-10 mx-auto mt-5">
  <div class="card mt-4 mb-4">
    <div class="card-body">
      <h3 class="text-center mb-3">Search Professionals across the world</h3>
      <%= search_form_for @q, url: root_path do |f| %>
        <div class="input-group mb-3">
          <%= f.search_field :city_or_country_cont, class: "form-control", placeholder: "Search by country or city", area: { label: "Search by country or city", describedby: "button-addon2" } %>
          <%= f.submit "Seach", class: "btn btn-primary", id: "button-addon2"%>
        </div>
      <% end %>
    </div>
  </div>
  
  <div class="row mt-4 mb-4">
    <% @users.each do |user| %>
      <div class="col-lg-4 mb-3 mt-3">
        <div class="card text-center shadow" style="min-height: 400px;">
          <div class="card-body">
            <%= image_tag "avatar.png", style: "width: 150px; border-radius: 50%; border: 2px solid #0d6efd;", class: 'mb-3' %>
            <div class="user-info" data-controller="user-name">
              <h5 data-user-name-target="name" data-action="click->user-name#getUserName"><%= user.name %></h5>
              <p class="lead"><%= user.profile_title %></p>
              <small class="text-primary"><%= user.country %></small><br>
              <%= link_to "View profile", member_path(user), class: "btn btn-primary mt-3" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Dev Community" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <% if flash.any? %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      <% end %>
      <div class="row justify-content-center">
        <div class="col-lg-10 max-auto">
          <%= render "shared/header" %>
        </div>
        <%= yield %>
        <div class="col-lg-10 max-auto">
          <%= render "shared/footer" %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/members/show.html.erb
<div class="col-lg-10 mx-auto mt-5">
  <div class="card mb-5">
    <div class="row">
      <div class="col-lg-4">
        <%= image_tag "avatar.png", class: "img-fluid" %>
      </div>
      <div class="col-lg-8">
        <div class="card-body">
          <h3 class="fw-bold"><%= @user.name %></h3>
          <p class="lead"><%= @user.profile_title %></p>
          <p class="lead text-primary"><%= @user.address %></p>
        </div>
      </div>
    </div>
  </div>

  <div class="card mb-5">
    <div class="card-body">
      <div class="row">
        <div class="col-lg-6">
          <div class="d-flex justify-content-start">
            <h3>About</h3>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="d-flex justify-content-end">
          </div>
        </div>
      </div>
      <p class="lead"><%= @user.about %></p>
    </div>
</div>

app/views/shared/_footer.html.erb
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md">
      <small class="d-block mb-3 text-muted">
        company@2024-2025
      </small>
    </div>
    <div class="col-lg-4">
      <h5>Features</h5>
      <ul class="list-unstyled text-small">
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="javascript:void(0)">About Us</a>
        </li>
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="javascript:void(0)">Contact Us</a>
        </li>
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="javascript:void(0)">Our Mission</a>
        </li>
      </ul>
    </div>
    <div class="col-lg-4">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="javascript:void(0)">Blog</a>
        </li>
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="javascript:void(0)">Careers</a>
        </li>
        <li class="mb-1">
          <a class="link-secondary text-decoration-none" href="javascript:void(0)">Profiles</a>
        </li>
      </ul>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <%= link_to "Dev Community", root_path, class: "navbar-brand", style: "padding-left: 20px;" %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home</a>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Profile", member_path(current_user), class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure you wanna sign out?" }, class: "nav-link active" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign in", new_user_session_path, class: "nav-link active" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>